/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyJNICalc */

#ifndef _Included_MyJNICalc
#define _Included_MyJNICalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyJNICalc
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MyJNICalc_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     MyJNICalc
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MyJNICalc_sub
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
